# name: 'Run Jest tests'

# on: [pull_request]

# jobs:
#   jest:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node: [12, 14, 16]
#     steps:
#       - uses: actions/checkout@v3
#       - name: Use Node.js ${{ matrix.node }}
#         uses: actions/setup-node@v3
#         with:
#           node-version: '14'
#           cache: 'yarn'
#       - name: Install dependencies
#         run: yarn install --frozen-lockfile
#       - name: Run jest tests
#         run: yarn test
#       - name: Run jest test coverage
#         run: yarn test:coverage
