name: 'Cypress UI tests'

on: [pull_request]

jobs:
  install-cache:
    name: Install and cache dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3
      - name: Cache yarn dependencies and cypress
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: ${{ runner.os }}-yarn-v1-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-v1
      - name: Install dependencies if cache invalid
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
  cypress:
    name: Run Cypress tests
    runs-on: ubuntu-latest
    needs: install-cache
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Restore yarn dependencies
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: ${{ runner.os }}-yarn-v1-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-v1
      - name: Build package styles
        run: yarn build:css
      # Run component tests
      - name: Cypress run component tests
        uses: cypress-io/github-action@v4
        with:
          record: false
          component: true
          command: yarn cypress:run-comp
      # Run interaction tests
      - name: Build Storybook
        run: yarn build-storybook
      - name: Cypress run e2e tests
        uses: cypress-io/github-action@v4
        with:
          record: false
          component: false
          command: |
            yarn concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
              "yarn http-server storybook-static --port 6006 --silent" \
              "yarn wait-on tcp:6006 && yarn test-storybook && yarn cypress:run-e2e"
